# Generated by Django 4.2.4 on 2023-11-12 10:49

import api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_role_delete_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Remetente')),
                ('to', api.TextField(help_text='Separar endereços de e-mail por ",".', verbose_name='Destinatário')),
                ('subject', api.CharField(max_length=255, verbose_name='Assunto')),
                ('content', api.TextField(verbose_name='Conteúdo')),
                ('sent_at', models.DateTimeField(null=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mails',
            },
            bases=(models.Model, api.ModelMixin),
        ),
    ]
